---
title: "Buttefly Rearing Information"
author: "Taylor Hatcher"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true 
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Background
This website can used for addressing any questions regarding butterfly lab rearing. If you can't find the information you are looking for her, please let Taylor Hatcher (taymhather@gmail.com) know and she will add any missing information. Butterly rearing in the lab involves a lot of moving parts and some planning. Hopefully this website will aide in those tasks and help facilitate a good workflow!

# Supplies 
Here are the links for the supplies we use in the lab and what channel to purchase them through:
<b> Bleach, petri dishes, latex gloves, lab tape, greenhouse soil, and paper towels</b> can be purchased via the  [Biology Stock Room](https://admin.biology.uw.edu/stockroom/login)

Other supplies for the lab can be purchased via [purchase path](https://www.pathology.washington.edu/purchasePATH/?DEPT=24:):
<br> [Butterfly Nectar](https://www.amazon.com/Birds-Choice-NP1005-Butterfly-Nectar/dp/B001QLKSL8/)
<br> [Butterfly Large Cages](https://www.amazon.com/RESTCLOUD-Insect-Butterfly-Habitat-Terrarium/dp/B074ZHXF48/)
<br> [Butterfly Square Cages 12x12x12](https://www.amazon.com/RESTCLOUD-Butterfly-Habitat-Terrarium-Protection/dp/B082X3L64V/)
<br> [Brassica Oleracea seeds](https://www.highmowingseeds.com/organic-non-gmo-champion-collards.html)
<br> [Sponges](https://www.amazon.com/Temede-Cellulose-Non-Scratch-Compressed-Household/dp/B09H2S77JG/)
<br> [Soft touch forceps](https://www.amazon.com/DR-Instruments-Entomology-Stainless-Steel-Construction/dp/B07B4767WR/)
<br> [Butterfly forceps](https://www.amazon.com/MMOBIEL-Stainless-Precision-Philately-Development/dp/B096MPLZ6Q/)
<br> [Glassine envelopes](https://www.amazon.com/Uline-Mini-Glassine-Paper-Bags/dp/B009N44XNO/)
<br> [Organic Fertilizer] (https://www.amazon.com/EB-Stone-Organic-Tomato-Vegetable/dp/B00BJAM7V0/)
<br> [Lab notebooks](https://www.amazon.com/DesignWorks-Ink-Standard-Personal-Journal/dp/B01FMRZYCE/)

# Rearing Chambers
<br> LSB 4th Floor Chambers
<br> B2 Conviron Chambers - contact Alex Hansen 

# Programming and Troubleshooting Chambers
It is important to have temperature loggers in any chambers running for experiments. You will need to check these frequently to ensure the chambers are behaving how they should. 

If you are having issues with the B2 Conviron Chambers, contact the building manager, Alex Hansen.

# LSB Greenhouse
Anyone working/volunteering in the greenhouse needs greenhouse access. You can request access with a keyform (found on the biology department admin website) via biokeys@uw.edu. After public building hours access needs special permission from the greenhouse manager. Anyone working in the greenhouse will need to meet and orient with the greenhouse manager. 

# UCAR Reservation Protocol
If you are needing to use a UCAR for research, you will have to first complete the UCAR training. You can find all of the information [here](https://transportation.uw.edu/getting-around/vehicle-rental-ucar)

# Caterpillar development timeline
When rearing caterpillars, it is important to be able to estimate the time they will be ready for experiments.
For Pieris rapae:
For 10-30°C 16L:8D treatment caterpillars usually take ~13 days from catching to fresh 4th instars. 
For 11-35°C 16L:8D treatment caterpillars usually take ~11 days from catching to fresh 4th instars.

For Pontia occidentalis:
It takes about a month from catching and setting up oviposition cages to adult butteflies.

# HOBO Loggers
There are 4 hobo loggers that record ambient temperature and relative humidity. You can connect to them via bluetooth on the HOBO app that is available in the app store. 

There are 3 hobo loggers used in the field that connect to thermocouples. If you need oriented to them, please schedule a meeting with Taylor.

# Volunteers
Anyone volunteering in the lab is required to fill out a volunteer form which should be returned to the department administrator. Email Taylor for the updated volunteer form. 







